# Generated by Django 5.1.1 on 2024-12-26 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food_List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titel', models.CharField(default='', max_length=100)),
                ('Price', models.CharField(default='', max_length=100)),
                ('Images', models.ImageField(upload_to='midea/FoodImages/')),
                ('Description', models.TextField()),
            ],
        ),
    ]
